[versions]
agp = "8.13.1"
android = "2.1.0"
annotation = "1.9.1"
hiltVersion = "2.57.2"
hiltWorkVersion = "1.3.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxCoroutinesCore = "1.10.2"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.1"
composeBom = "2025.12.00"
jetbrainsKotlinJvm = "2.2.21"
appcompat = "1.7.1"
loggingInterceptor = "5.3.2"
material = "1.13.0"
materialIconsExtended = "1.7.8"
navigationCompose = "2.9.6"
pagingCompose = "3.4.0-alpha04"
pagingRuntime = "3.3.6"
retrofit = "3.0.0"
roomVersion = "2.8.4"
moshi = "1.15.2"
converterMoshi = "3.0.0"
gradle = "8.13.1"
workManagerVersion = "2.11.0"
ksp = "2.2.20-2.0.4"
coilCompose = "3.3.0"
detekt = "1.23.8"
desugar_jdk_libs = "2.1.5"
runner = "1.7.0"
mockk = "1.14.7"
striktCore = "0.35.1"

javaVersion = "17"
compileSdk = "36"
minSdk = "23"

[libraries]
android = { module = "se.ansman.dagger.auto:android", version.ref = "android" }
android-api = { module = "se.ansman.dagger.auto:android-api", version.ref = "android" }
android-testing = { module = "se.ansman.dagger.auto:android-testing", version.ref = "android" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWorkVersion" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltWorkVersion" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomVersion" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workManagerVersion" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workManagerVersion" }
compiler = { module = "se.ansman.dagger.auto:compiler", version.ref = "android" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hiltVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltVersion" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWorkVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }
build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
strikt-core = { module = "io.strikt:strikt-core", version.ref = "striktCore" }

[bundles]
test-common = [
    "junit",
    "mockk",
    "strikt-core",
]
test-common-android = [
    "androidx-junit",
    "androidx-runner",
    "strikt-core",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
android-library = { id = "com.android.library", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "roomVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
detekt-plugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

conventions-compose = { id = "ru.agrachev.convention.plugins.compose", version = "unspecified" }
conventions-hilt = { id = "ru.agrachev.convention.plugins.hilt", version = "unspecified" }
conventions-hilt-autobind = { id = "ru.agrachev.convention.plugins.hilt.autobind", version = "unspecified" }
conventions-android-library = { id = "ru.agrachev.convention.plugins.androidLibrary", version = "unspecified" }
conventions-android-application = { id = "ru.agrachev.convention.plugins.androidApplication", version = "unspecified" }
conventions-kotlin-library = { id = "ru.agrachev.convention.plugins.kotlinLibrary", version = "unspecified" }
